import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 방금 만든 파일 임포트
import { ThemeProvider } from "@/src/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 1. 여기에 suppressHydrationWarning 추가
    <html lang="ko" suppressHydrationWarning>
      <body className={inter.className}>
        {/* 2. ThemeProvider로 감싸기 */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}